# Effective degrees of freedom / number of parameters

One thing that your learn once you start using linear mixed models (multulevel) models is that degrees of freedom used up by the model is less than number of parameters, so the total number is called number of _effective_ parameters / degrees of freedom. This is because each parameter (whether it is formally "fixed" or "random") can use up 1 degree of freedom. It will use full one degree of freedom, if it can take _any_ value. In other words, a parameter with flat prior takes up 1 degree of freedom. In yet other words, a parameter takes one full degree of freedom if its  prior distribution has _infinite_ variance (a different way to say that it can take any value and its prior is flat). Conversely, if prior distribution for the parameter has _zero_ variance, then it is fixed (a constant!) and take zero degrees of freedom. Finally, if prior distribution for the parameter has non-zero _finite_ variance (whatever it is), it uses up a fraction of the degree of freedom. How much it uses up depends on the variance.

This is why fixed parameters in frequentist statistics use full degree of freedom (flat priors!) but same "fixed" parameters will use less than one in Bayesian models with non-flat priors (even weakly regularizing priors mean that you are not enjoying the full freedom). Similarly, a random effect in repeated measures ANOVA uses one degree of freedom because it has flat priors (can take any value, no shrinkage) but only a fraction in linear mixed models, because in LMM random effects come from a Gaussian distribution with finite variance (shrinkage!).

